<a href="https://colab.research.google.com/github/uxue-sudupe/R-tailerrak/blob/main/notebook/5_02_data_manipulation_eu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TAILERRA: Pivot Longer, Pivot Wider eta Join-ak, Tidyr eta Dplyr-ekin**

![](https://raw.githubusercontent.com/uxue-sudupe/R-tailerrak/main/notebook/img/tidyr-longer-wider.gif)

Gaur bi pakete erabiliko ditugu:

*   tidyr -> datuen forma aldatzeko (pivot_longer, pivot_wider)
*   dplyr -> datuak filtratu, ordenatu eta elkartzeko (join)

Biak tidyverse ekosistemaren parte dira.

Cheatsheet-ak:

*   https://rstudio.github.io/cheatsheets/html/tidyr.html
*   https://rstudio.github.io/cheatsheets/html/data-transformation.html

Bi paketeak instalatu eta kargatu daitezke, edo "tidyverse" paketea erabili:

In [1]:

install.packages("tidyverse")
library(tidyverse)

# Edo
# install.packages(c("dplyr", "tidyr"))
# library(dplyr)
# library(tidyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors


**1. TIDY DATA**

Hadley Wickham-en ideia nagusia:
 - Aldagai bakoitza -> zutabe bat
 - Behaketa bakoitza -> errenkada bat
 - Balio bakoitza -> gelaxka bat

Gaur ikusiko dugu nola moldatu datuak forma batetik bestera

Datuak horrela egituratuta topatu ditzakegu

In [2]:
bpg_urtea_zabal <- tibble(
  lurraldea = c("Araba", "Bizkaia", "Gipuzkoa"),

  `2020` = c(11823563, 36187794, 24668564),
  `2021` = c(12819599, 39256450, 26633353),
  `2022` = c(13826025, 44068322, 28820064),
  `2023` = c(14998283, 47148928, 31095360),
  `2024` = c(15698420, 49867283, 32724112)
)

bpg_urtea_zabal

  lurraldea 2020     2021     2022     2023     2024
1 Araba     11823563 12819599 13826025 14998283 15698420
2 Bizkaia   36187794 39256450 44068322 47148928 49867283
3 Gipuzkoa  24668564 26633353 28820064 31095360 32724112

Edo horrela:

In [3]:
bpg_lurraldea_zabal <- tibble(
  urtea = c(2020, 2021, 2022, 2023, 2024),
  EAE = c(72679921, 78709402, 86714411, 93242571, 98289815),
  Araba = c(11823563, 12819599, 13826025, 14998283, 15698420),
  Bizkaia = c(36187794, 39256450, 44068322, 47148928, 49867283),
  Gipuzkoa = c(24668564, 26633353, 28820064, 31095360, 32724112)
)

bpg_lurraldea_zabal

  urtea EAE      Araba    Bizkaia  Gipuzkoa
1 2020  72679921 11823563 36187794 24668564
2 2021  78709402 12819599 39256450 26633353
3 2022  86714411 13826025 44068322 28820064
4 2023  93242571 14998283 47148928 31095360
5 2024  98289815 15698420 49867283 32724112

Galdera:
Urteak benetan aldagai berriak dira?

Ez. Urtea (edo lurraldea) aldagai bakarra da.

Beraz, datu hauek "zabalegiak" dira.

In [4]:
?pivot_longer

**1.2. Pivot Longer, egitura txukuntzeko**

In [5]:
bpg_txukun1 <- bpg_urtea_zabal %>%
               pivot_longer(
               cols = `2020`:`2024`,
               names_to = "urtea",
               values_to = "bpg")
bpg_txukun1

   lurraldea urtea bpg
1  Araba     2020  11823563
2  Araba     2021  12819599
3  Araba     2022  13826025
4  Araba     2023  14998283
5  Araba     2024  15698420
6  Bizkaia   2020  36187794
7  Bizkaia   2021  39256450
8  Bizkaia   2022  44068322
9  Bizkaia   2023  47148928
10 Bizkaia   2024  49867283
11 Gipuzkoa  2020  24668564
12 Gipuzkoa  2021  26633353
13 Gipuzkoa  2022  28820064
14 Gipuzkoa  2023  31095360
15 Gipuzkoa  2024  32724112

In [6]:
bpg_txukun2 <- bpg_lurraldea_zabal %>%
              pivot_longer(
              cols = EAE:Gipuzkoa,
              names_to = "lurraldea",
              values_to = "bpg")
bpg_txukun2

   urtea lurraldea bpg
1  2020  EAE       72679921
2  2020  Araba     11823563
3  2020  Bizkaia   36187794
4  2020  Gipuzkoa  24668564
5  2021  EAE       78709402
6  2021  Araba     12819599
7  2021  Bizkaia   39256450
8  2021  Gipuzkoa  26633353
9  2022  EAE       86714411
10 2022  Araba     13826025
11 2022  Bizkaia   44068322
12 2022  Gipuzkoa  28820064
13 2023  EAE       93242571
14 2023  Araba     14998283
15 2023  Bizkaia   47148928
16 2023  Gipuzkoa  31095360
17 2024  EAE       98289815
18 2024  Araba     15698420
19 2024  Bizkaia   49867283
20 2024  Gipuzkoa  32724112

Beste adibide bat

In [7]:
errenta_oso_zabal <- tibble(
  sexua = c("Guztira", "Gizonak", "Emakumeak"),

  EAE_2020 = c(22343, 27422, 17667),
  EAE_2021 = c(23313, 28360, 18659),
  EAE_2022 = c(25061, 30356, 20180),
  EAE_2023 = c(26271, 31641, 21322),

  Araba_2020 = c(21516, 26236, 17050),
  Araba_2021 = c(22373, 27148, 17853),
  Araba_2022 = c(23660, 28471, 19109),
  Araba_2023 = c(24921, 29886, 20238)
)

errenta_oso_zabal

  sexua     EAE_2020 EAE_2021 EAE_2022 EAE_2023 Araba_2020 Araba_2021
1 Guztira   22343    23313    25061    26271    21516      22373
2 Gizonak   27422    28360    30356    31641    26236      27148
3 Emakumeak 17667    18659    20180    21322    17050      17853
  Araba_2022 Araba_2023
1 23660      24921
2 28471      29886
3 19109      20238

In [8]:
errenta_txukun2 <- errenta_oso_zabal %>%
  pivot_longer(
    cols = -sexua,
    names_to = c("lurraldea", "urtea"),
    names_sep = "_",
    values_to = "errenta"
  )

errenta_txukun2

   sexua     lurraldea urtea errenta
1  Guztira   EAE       2020  22343
2  Guztira   EAE       2021  23313
3  Guztira   EAE       2022  25061
4  Guztira   EAE       2023  26271
5  Guztira   Araba     2020  21516
6  Guztira   Araba     2021  22373
7  Guztira   Araba     2022  23660
8  Guztira   Araba     2023  24921
9  Gizonak   EAE       2020  27422
10 Gizonak   EAE       2021  28360
11 Gizonak   EAE       2022  30356
12 Gizonak   EAE       2023  31641
13 Gizonak   Araba     2020  26236
14 Gizonak   Araba     2021  27148
15 Gizonak   Araba     2022  28471
16 Gizonak   Araba     2023  29886
17 Emakumeak EAE       2020  17667
18 Emakumeak EAE       2021  18659
19 Emakumeak EAE       2022  20180
20 Emakumeak EAE       2023  21322
21 Emakumeak Araba     2020  17050
22 Emakumeak Araba     2021  17853
23 Emakumeak Araba     2022  19109
24 Emakumeak Araba     2023  20238

Benetako kasu bat

 Giza garapenaren indizeko datuak erabiliko ditugu:
 https://hdr.undp.org/sites/default/files/2025_HDR/HDR25_Composite_indices_complete_time_series.csv

In [12]:
url <- "https://raw.githubusercontent.com/uxue-sudupe/R-tailerrak/main/data/HDR_Composite_indices_complete_time_series.csv"

hdi <- read.csv(url)

hdi

Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 2 is invalid UTF-8

Traceback:
1. sapply(x, f, simplify = simplify)
2. lapply(X = X, FUN = FUN, ...)
3. FUN(X[[i]], ...)
4. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. doTryCatch(return(expr), name, parentenv, handler)
8. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
9. repr::mime2repr[[mime]](obj)
10. repr_markdown.data.frame(obj)
11. repr_matrix_generic(obj, "\n%s\n\n%s%s\n", sprintf("|%%s\n|%s|\n",
  .     underline), NULL, " <!--/--> |", " %s |", "%s", "|%s\n",
  .     " %s |", " %s |", escape_fun = markdown_escape, rows = rows,
  .     cols = cols, ...)
12. lapply(seq_len(nrow(x)), function(r) {
  .     row <- escape_fun(slice_row(x, r))
  .     cells <- sprintf(cell, row)
  .     if (has_rownames) {
  .         row_head <- sprintf(row_head, escape_fun(rownames(x)[[r]]))
  .         cells <- c(row_head, cells)
  .     }
  .     sprintf(row_wrap, paste(cells, collapse = ""))
  . })
13. FUN(X[[i]], ...)
14. escape_fun(slice_row(x, r))
15. html_escape(values, do_spaces = FALSE)
16. gsub(chr, html_specials[[chr]], text, fixed = TRUE)
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 2 is invalid UTF-8”
ERROR while rich displaying an object: Error in gsub(" &\\", "\\", r, fixed = TRUE): input string 1 is invalid UTF-8

Traceback:
1. sapply(x, f, simplify = simplify)
2. lapply(X = X, FUN = FUN, ...)
3. FUN(X[[i]], ...)
4. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. doTryCatch(return(expr), name, parentenv, handler)
8. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
9. repr::mime2repr[[mime]](obj)
10. repr_latex.data.frame(obj)
11. gsub(" &\\", "\\", r, fixed = TRUE)
Warning message in grepl("<html.*>", data[["text/html"]], ignore.case = TRUE):
“unable to translate '<table class="dataframe">
<caption>A data.frame: 206 × 1112</caption>
<thead>
	<tr><th scope=col>iso3</th><th scope=col>country</th><th scope=col>hdicode</th><th scope=col>region</th><th scope=col>hdi_rank_2023</th><th scope=col>hdi_1990</th><th scope...' to a wide string”
Warning message in grepl("<html.*>", data[["text/html"]], ignore.case = TRUE):
“input string 1 is invalid”

    iso3      country                            hdicode   region hdi_rank_2023
1   AFG       Afghanistan                        Low       SA     181
2   ALB       Albania                            Very High ECA     71
3   DZA       Algeria                            High      AS      96
4   AND       Andorra                            Very High         32
5   AGO       Angola                             Medium    SSA    148
6   ATG       Antigua and Barbuda                Very High LAC     53
7   ARG       Argentina                          Very High LAC     47
8   ARM       Armenia                            Very High ECA     69
9   AUS       Australia                          Very High          7
10  AUT       Austria                            Very High         22
11  AZE       Azerbaijan                         High      ECA     81
12  BHS       Bahamas                            Very High LAC     66
13  BHR       Bahrain                            Very High AS      38
14  BGD       Bangladesh                         Medium    SA     130
15  BRB       Barbados                           Very High LAC     69
16  BLR       Belarus                            Very High ECA     65
17  BEL       Belgium                            Very High         10
18  BLZ       Belize                             High      LAC    115
19  BEN       Benin                              Low       SSA    173
20  BTN       Bhutan                             Medium    SA     125
21  BOL       Bolivia (Plurinational State of)   High      LAC    108
22  BIH       Bosnia and Herzegovina             Very High ECA     74
23  BWA       Botswana                           High      SSA    111
24  BRA       Brazil                             High      LAC     84
25  BRN       Brunei Darussalam                  Very High EAP     60
26  BGR       Bulgaria                           Very High         55
27  BFA       Burkina Faso                       Low       SSA    186
28  BDI       Burundi                            Low       SSA    187
29  CPV       Cabo Verde                         Medium    SSA    135
30  KHM       Cambodia                           Medium    EAP    151
⋮   ⋮         ⋮                                  ⋮         ⋮      ⋮
177 TON       Tonga                              High      EAP     92
178 TTO       Trinidad and Tobago                Very High LAC     72
179 TUN       Tunisia                            High      AS     105
180 TKM       Turkmenistan                       High      ECA     95
181 TUV       Tuvalu                             Medium    EAP    129
182 TUR       T\xfcrkiye                         Very High ECA     51
183 UGA       Uganda                             Medium    SSA    157
184 UKR       Ukraine                            High      ECA     87
185 ARE       United Arab Emirates               Very High AS      15
186 GBR       United Kingdom                     Very High         13
187 USA       United States                      Very High         17
188 URY       Uruguay                            Very High LAC     48
189 UZB       Uzbekistan                         High      ECA    107
190 VUT       Vanuatu                            Medium    EAP    146
191 VEN       Venezuela (Bolivarian Republic of) High      LAC    121
192 VNM       Viet Nam                           High      EAP     93
193 YEM       Yemen                              Low       AS     184
194 ZMB       Zambia                             Medium    SSA    154
195 ZWE       Zimbabwe                           Medium    SSA    153
196 ZZA.VHHD  Very high human development                          NA
197 ZZB.HHD   High human development                               NA
198 ZZC.MHD   Medium human development                             NA
199 ZZD.LHD   Low human development                                NA
200 ZZE.AS    Arab States                                          NA
201 ZZF.EAP   East Asia and the Pacific                            NA
202 ZZG.ECA   Europe and Central Asia                              NA
203 ZZH.LAC   Latin America and the Caribbean                      NA
204 ZZI.SA    South Asia                                           NA
205 ZZJ.SSA   Sub-Saharan Africa                                   NA
206 ZZK.WORLD World                                                NA
    hdi_1990 hdi_1991 hdi_1992 hdi_1993 hdi_1994 ⋯ pop_total_2014
1   0.285    0.291    0.301    0.311    0.305    ⋯  32.7925230
2   0.654    0.638    0.622    0.624    0.629    ⋯   2.9037495
3   0.595    0.596    0.601    0.603    0.603    ⋯  39.2050305
4      NA       NA       NA       NA       NA    ⋯   0.0737370
5      NA       NA       NA       NA       NA    ⋯  27.1607695
6      NA       NA       NA       NA       NA    ⋯   0.0887650
7   0.733    0.739    0.743    0.748    0.753    ⋯  43.0240715
8   0.663    0.652    0.618    0.621    0.625    ⋯   2.9224220
9   0.867    0.868    0.868    0.872    0.873    ⋯  23.5956005
10  0.832    0.835    0.841    0.845    0.851    ⋯   8.5478175
11     NA       NA       NA       NA       NA    ⋯   9.6311380
12  0.762    0.762    0.762    0.763    0.765    ⋯   0.3822980
13  0.734    0.728    0.728    0.732    0.732    ⋯   1.3128480
14  0.397    0.395    0.411    0.419    0.426    ⋯ 157.9649285
15  0.730    0.732    0.732    0.735    0.740    ⋯   0.2783480
16     NA       NA       NA       NA       NA    ⋯   9.4727075
17  0.824    0.829    0.845    0.860    0.868    ⋯  11.2101190
18  0.617    0.626    0.634    0.640    0.643    ⋯   0.3489225
19  0.351    0.358    0.363    0.371    0.375    ⋯  11.0300035
20     NA       NA       NA       NA       NA    ⋯   0.7331395
21  0.552    0.561    0.568    0.577    0.586    ⋯  10.8488885
22     NA       NA       NA       NA       NA    ⋯   3.5648290
23  0.590    0.590    0.589    0.588    0.580    ⋯   2.1720440
24  0.641    0.645    0.648    0.654    0.659    ⋯ 200.0851270
25  0.781    0.782    0.782    0.783    0.782    ⋯   0.4167505
26  0.706    0.706    0.709    0.711    0.713    ⋯   7.2234495
27     NA       NA       NA       NA       NA    ⋯  18.2294610
28  0.294    0.296    0.294    0.265    0.298    ⋯  10.7997855
29     NA       NA       NA       NA       NA    ⋯   0.5123255
30  0.387    0.392    0.396    0.399    0.400    ⋯  15.3967715
⋮   ⋮        ⋮        ⋮        ⋮        ⋮        ⋱ ⋮
177 0.641    0.649    0.654    0.660    0.670    ⋯    0.1066090
178 0.661    0.665    0.665    0.667    0.672    ⋯    1.4211315
179 0.569    0.575    0.582    0.587    0.598    ⋯   11.2742880
180    NA       NA       NA       NA       NA    ⋯    6.0752830
181 0.566    0.570    0.566    0.579    0.586    ⋯    0.0109840
182 0.598    0.602    0.608    0.615    0.616    ⋯   78.0361540
183 0.342    0.345    0.339    0.347    0.350    ⋯   36.3955385
184 0.750    0.743    0.733    0.721    0.706    ⋯   45.9723805
185 0.713    0.724    0.729    0.736    0.742    ⋯    8.2368745
186 0.812    0.816    0.824    0.827    0.836    ⋯   64.8659165
187 0.878    0.878    0.882    0.884    0.887    ⋯  323.1153770
188 0.713    0.717    0.719    0.722    0.727    ⋯    3.3563345
189    NA       NA       NA       NA       NA    ⋯   30.2229935
190    NA       NA       NA       NA       NA    ⋯    0.2602395
191 0.658    0.669    0.676    0.680    0.681    ⋯   30.2540790
192 0.499    0.509    0.521    0.531    0.543    ⋯   91.6795780
193 0.359    0.364    0.370    0.377    0.382    ⋯   30.2263090
194 0.422    0.416    0.414    0.417    0.413    ⋯   15.8953150
195 0.500    0.502    0.487    0.483    0.482    ⋯   14.2073585
196 0.797    0.800    0.802    0.804    0.809    ⋯ 1536.5554050
197 0.569    0.574    0.580    0.586    0.591    ⋯ 2877.2026890
198 0.439    0.440    0.445    0.449    0.453    ⋯ 2179.7908730
199 0.346    0.348    0.352    0.356    0.361    ⋯  728.5511030
200 0.550    0.552    0.561    0.571    0.577    ⋯  396.8445680
201 0.514    0.522    0.531    0.541    0.550    ⋯ 2062.3287920
202 0.674    0.671    0.664    0.659    0.654    ⋯  237.9338495
203 0.648    0.653    0.657    0.661    0.666    ⋯  608.7672810
204 0.454    0.458    0.464    0.468    0.472    ⋯ 1849.1679180
205 0.405    0.409    0.408    0.411    0.413    ⋯  945.8423185
206 0.608    0.611    0.614    0.617    0.620    ⋯ 7347.5874590
    pop_total_2015 pop_total_2016 pop_total_2017 pop_total_2018 pop_total_2019
1    33.8317635     34.7006120     35.6889345     36.7430390     37.8561210
2     2.8986320      2.8978665      2.8982425      2.8942310      2.8850095
3    40.0195290     40.8507210     41.6892990     42.5050350     43.2945460
4     0.0721735      0.0721815      0.0737625      0.0751620      0.0764735
5    28.1577980     29.1830700     30.2348390     31.2971550     32.3756325
6     0.0894090      0.0899690      0.0904680      0.0909260      0.0913635
7    43.4770120     43.9003135     44.2888940     44.6548815     44.9734655
8     2.9211775      2.9187925      2.9149635      2.9099645      2.9039715
9    23.9480020     24.3299630     24.7310385     25.1197055     25.4827140
10    8.6440385      8.7379155      8.7987775      8.8416505      8.8808760
11    9.7528500      9.8684280      9.9685095     10.0397845     10.1104750
12    0.3853465      0.3880555      0.3904850      0.3927175      0.3946745
13    1.3696500      1.4296040      1.4819950      1.4976255      1.4856705
14  159.3831790    160.8119325    162.1861465    163.5231035    164.9130550
15    0.2789900      0.2795975      0.2801710      0.2807105      0.2812075
16    9.4872930      9.4990635      9.4957895      9.4800310      9.4354195
17   11.2753345     11.3327005     11.3765805     11.4286050     11.4906180
18    0.3563330      0.3647050      0.3732015      0.3802265      0.3858285
19   11.3606810     11.6978415     12.0397800     12.3833475     12.7267550
20    0.7406180      0.7478660      0.7543345      0.7597590      0.7648240
21   11.0147050     11.1800195     11.3445875     11.5083680     11.6713855
22    3.5185405      3.4730030      3.4286825      3.3870000      3.3455330
23    2.2032730      2.2347755      2.2667470      2.2991410      2.3320830
24  201.6755320    203.2181135    204.7034450    206.1072605    207.4554595
25    0.4222115      0.4275640      0.4327720      0.4378095      0.4426800
26    7.1775170      7.1274340      7.0756355      7.0247455      6.9754690
27   18.7774870     19.3348555     19.8944070     20.4382880     20.9619525
28   11.0475800     11.2394510     11.5067620     11.8594460     12.2553365
29    0.5123935      0.5125545      0.5128930      0.5134150      0.5141040
30   15.6232505     15.8528030     16.0733725     16.2745215     16.4813040
⋮   ⋮              ⋮              ⋮              ⋮              ⋮
177    0.106095       0.1055240      0.1053555      0.1055665      0.1056695
178    1.429188       1.4370260      1.4452605      1.4705185      1.4848940
179   11.402264      11.5286735     11.6504985     11.7655145     11.8750810
180    6.215770       6.3600410      6.5070610      6.6555240      6.8039445
181    0.010963       0.0109295      0.0108690      0.0107505      0.0105810
182   80.014226      81.6520885     83.0836620     84.4159685     85.3576720
183   37.531445      38.7991520     40.1773880     41.5658310     42.9996375
184   45.784896      45.6168320     45.4360415     45.2089070     44.9574580
185    8.674633       9.0308730      9.2343270      9.3468700      9.3778475
186   65.382110      65.8933580     66.3544710     66.7524750     67.1109580
187  326.126496     329.1794265    332.2046595    335.0564975    337.7900665
188    3.368017       3.3792830      3.3884375      3.3945340      3.3972055
189   30.749347      31.2845680     31.8191775     32.3734905     32.9647010
190    0.266101       0.2720865      0.2785070      0.2852585      0.2919845
191   30.573972      30.7657205     30.5653235     29.8075920     28.9380980
192   92.823254      94.0001165     95.1769770     96.2373195     97.1737755
193   31.159379      32.1090100     33.0909215     34.0851820     35.1114075
194   16.399089      16.9144230     17.4413195     17.9735690     18.5138395
195   14.399013      14.6002940     14.8124820     15.0344520     15.2713675
196 1548.326505    1559.6892420   1569.4678000   1577.9222270   1585.7399590
197 2903.618825    2928.3832790   2952.7742870   2975.2042260   2994.6873660
198 2212.499091    2246.2716850   2280.1317940   2313.3696680   2346.5945820
199  746.373049     764.3806075    783.3072825    803.3679915    824.0920225
200  406.159446     415.2329930    423.5943470    431.5141145    439.8016215
201 2078.251006    2093.7351670   2109.3996820   2123.0087810   2134.1713150
202  240.937124     243.6498170    246.1310110    248.4508850    250.3824845
203  614.831634     620.7538580    626.5036065    632.0055915    637.1857395
204 1871.872058    1894.4653460   1917.1446040   1939.5377620   1961.7292040
205  971.462925     997.2587125   1023.3530590   1050.3554500   1077.7767850
206 7436.429577    7524.4604160   7611.5365490   7695.8334150   7777.1896710
    pop_total_2020 pop_total_2021 pop_total_2022 pop_total_2023
1    39.0689790     40.0004120     40.5788420     41.4547610
2     2.8719535      2.8496355      2.8276080      2.8116550
3    44.0420910     44.7610990     45.4773895     46.1642190
4     0.0773800      0.0783635      0.0797050      0.0808560
5    33.4511325     34.5324290     35.6350290     36.7499060
6     0.0918460      0.0923490      0.0928400      0.0933155
7    45.1919645     45.3122815     45.4079040     45.5384010
8     2.8908925      2.8703485      2.8808745      2.9433930
9    25.7437910     25.9564175     26.2009845     26.4511240
10    8.9214050      8.9670565      9.0646770      9.1304290
11   10.1817300     10.2343705     10.2953040     10.3182070
12    0.3958625      0.3963730      0.3975385      0.3994405
13    1.4830770      1.5017635      1.5334590      1.5696655
14  166.2980240    167.6588545    169.3848975    171.4669900
15    0.2816980      0.2821465      0.2823180      0.2823360
16    9.3509440      9.2513650      9.1732370      9.1156800
17   11.5401070     11.5708435     11.6418200     11.7128930
18    0.3908115      0.3953465      0.4027330      0.4111055
19   13.0701690     13.4134170     13.7595005     14.1110345
20    0.7700060      0.7754415      0.7809145      0.7863850
21   11.8162995     11.9373595     12.0771540     12.2441595
22    3.2993495      3.2449075      3.2048020      3.1850730
23    2.3658935      2.4014405      2.4398915      2.4802445
24  208.6608425    209.5502940    210.3064145    211.1407290
25    0.4474035      0.4517205      0.4553695      0.4589485
26    6.9336520      6.8772255      6.8258640      6.7958030
27   21.4786895     21.9952430     22.5090385     23.0257760
28   12.6170360     12.9654815     13.3210975     13.6894495
29    0.5146795      0.5166490      0.5197410      0.5223305
30   16.7254735     16.9743055     17.2017235     17.4238805
⋮   ⋮              ⋮              ⋮              ⋮
177    0.1057035      0.1054895      0.1050420      0.1045975
178    1.4810235      1.4877175      1.4959215      1.5029325
179   11.9740570     12.0486225     12.1193335     12.2004310
180    6.9499120      7.0920435      7.2301930      7.3644380
181    0.0103995      0.0101935      0.0099920      0.0098155
182   86.0916915     86.6862525     87.0584725     87.2705015
183   44.4571525     45.9109300     47.3127195     48.6566015
184   44.6800145     44.2986400     41.0487660     37.7328355
185    9.4485240      9.7890480     10.2420865     10.6420810
186   67.3518615     67.6687920     68.1793155     68.6829625
187  339.4361585    340.1614410    341.5340455    343.4773350
188    3.3989680      3.3966945      3.3909130      3.3880805
189   33.5863720     34.2436955     34.9389555     35.6523070
190    0.2988585      0.3058685      0.3130465      0.3204085
191   28.4440775     28.2378260     28.2130165     28.3008540
192   98.0791910     98.9350985     99.6806550    100.3521915
193   36.1348635     37.1402305     38.2228755     39.3907990
194   19.0593950     19.6036075     20.1529380     20.7239650
195   15.5268885     15.7972100     16.0690555     16.3408215
196 1590.6797420   1593.0648320   1599.4279840   1607.2274740
197 3011.2120340   3024.0181850   3032.6756440   3040.8516300
198 2379.3050620   2409.9328320   2440.7488440   2473.6314000
199  845.5198010    867.1531120    888.3247805    909.7896745
200  448.0935260    456.4213775    466.3148890    476.4974840
201 2142.9329570   2148.6144460   2152.6520590   2155.6311150
202  252.0509980    253.4048660    251.9116935    250.3006245
203  641.7375400    645.5013085    649.4252890    653.9527325
204 1983.5103940   2003.2634280   2022.4672880   2043.0831600
205 1105.6140700   1133.7105930   1162.0425810   1191.5216750
206 7852.8910010   7920.4400210   7987.5450280   8057.9573390

In [13]:
# Zutabe asko ditu, herrialdeen izenak eta giza garapenaren indizea dutenak bakarrik hartuko ditugu

hdi_bakarrik <- hdi %>%
  select(country, hdi_1990:hdi_2023)

head(hdi_bakarrik)

  country             hdi_1990 hdi_1991 hdi_1992 hdi_1993 hdi_1994 hdi_1995
1 Afghanistan         0.285    0.291    0.301    0.311    0.305    0.329
2 Albania             0.654    0.638    0.622    0.624    0.629    0.638
3 Algeria             0.595    0.596    0.601    0.603    0.603    0.608
4 Andorra                NA       NA       NA       NA       NA       NA
5 Angola                 NA       NA       NA       NA       NA       NA
6 Antigua and Barbuda    NA       NA       NA       NA       NA       NA
  hdi_1996 hdi_1997 hdi_1998 ⋯ hdi_2014 hdi_2015 hdi_2016 hdi_2017 hdi_2018
1 0.334    0.338    0.338    ⋯ 0.497    0.496    0.495    0.496    0.498
2 0.647    0.645    0.659    ⋯ 0.797    0.797    0.797    0.798    0.801
3 0.615    0.624    0.634    ⋯ 0.732    0.737    0.743    0.746    0.749
4    NA       NA       NA    ⋯ 0.866    0.869    0.872    0.873    0.875
5    NA       NA       NA    ⋯ 0.577    0.603    0.609    0.610    0.611
6    NA       NA       NA    ⋯ 0.837    0.839    0.842    0.845    0.850
  hdi_2019 hdi_2020 hdi_2021 hdi_2022 hdi_2023
1 0.507    0.501    0.486    0.495    0.496
2 0.805    0.794    0.794    0.806    0.810
3 0.753    0.742    0.755    0.761    0.763
4 0.876    0.851    0.871    0.893    0.913
5 0.611    0.610    0.609    0.615    0.616
6 0.851    0.840    0.843    0.848    0.851

In [14]:
hdi_txukun <-  hdi_bakarrik %>% pivot_longer(
    cols = starts_with("hdi_"),
    names_to = "urtea",
    names_prefix = "hdi_",
    values_to = "ggi"
  )

hdi_txukun

     country     urtea ggi
1    Afghanistan 1990  0.285
2    Afghanistan 1991  0.291
3    Afghanistan 1992  0.301
4    Afghanistan 1993  0.311
5    Afghanistan 1994  0.305
6    Afghanistan 1995  0.329
7    Afghanistan 1996  0.334
8    Afghanistan 1997  0.338
9    Afghanistan 1998  0.338
10   Afghanistan 1999  0.347
11   Afghanistan 2000  0.351
12   Afghanistan 2001  0.355
13   Afghanistan 2002  0.383
14   Afghanistan 2003  0.392
15   Afghanistan 2004  0.408
16   Afghanistan 2005  0.417
17   Afghanistan 2006  0.426
18   Afghanistan 2007  0.442
19   Afghanistan 2008  0.446
20   Afghanistan 2009  0.458
21   Afghanistan 2010  0.465
22   Afghanistan 2011  0.474
23   Afghanistan 2012  0.484
24   Afghanistan 2013  0.492
25   Afghanistan 2014  0.497
26   Afghanistan 2015  0.496
27   Afghanistan 2016  0.495
28   Afghanistan 2017  0.496
29   Afghanistan 2018  0.498
30   Afghanistan 2019  0.507
⋮    ⋮           ⋮     ⋮
6975 World       1994  0.620
6976 World       1995  0.625
6977 World       1996  0.631
6978 World       1997  0.636
6979 World       1998  0.641
6980 World       1999  0.646
6981 World       2000  0.651
6982 World       2001  0.657
6983 World       2002  0.662
6984 World       2003  0.669
6985 World       2004  0.675
6986 World       2005  0.681
6987 World       2006  0.688
6988 World       2007  0.694
6989 World       2008  0.698
6990 World       2009  0.701
6991 World       2010  0.707
6992 World       2011  0.713
6993 World       2012  0.717
6994 World       2013  0.721
6995 World       2014  0.726
6996 World       2015  0.731
6997 World       2016  0.735
6998 World       2017  0.739
6999 World       2018  0.741
7000 World       2019  0.745
7001 World       2020  0.742
7002 World       2021  0.742
7003 World       2022  0.752
7004 World       2023  0.756

**1.2. PIVOT_WIDER()**

 Orain alderantziz egingo dugu

 Longer -> Wider
 Wider -> Longer

In [15]:

hdi_berriz_zabal <- hdi_txukun %>%
  pivot_wider(
    names_from = urtea,
#   names_prefix = "hdi_",
    values_from = ggi
  )

hdi_berriz_zabal

Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
ERROR while rich displaying an object: Error in gsub(chr, html_specials[[chr]], text, fixed = TRUE): input string 1 is invalid UTF-8

Traceback:
1. sapply(x, f, simplify = simplify)
2. lapply(X = X, FUN = FUN, ...)
3. FUN(X[[i]], ...)
4. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. doTryCatch(return(expr), name, parentenv, handler)
8. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
9. repr::mime2repr[[mime]](obj)
10. repr_markdown.data.frame(obj)
11. repr_matrix_generic(obj, "\n%s\n\n%s%s\n", sprintf("|%%s\n|%s|\n",
  .     underline), NULL, " <!--/--> |", " %s |", "%s", "|%s\n",
  .     " %s |", " %s |", escape_fun = markdown_escape, rows = rows,
  .     cols = cols, ...)
12. lapply(seq_len(nrow(x)), function(r) {
  .     row <- escape_fun(slice_row(x, r))
  .     cells <- sprintf(cell, row)
  .     if (has_rownames) {
  .         row_head <- sprintf(row_head, escape_fun(rownames(x)[[r]]))
  .         cells <- c(row_head, cells)
  .     }
  .     sprintf(row_wrap, paste(cells, collapse = ""))
  . })
13. FUN(X[[i]], ...)
14. escape_fun(slice_row(x, r))
15. html_escape(values, do_spaces = FALSE)
16. gsub(chr, html_specials[[chr]], text, fixed = TRUE)
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
Warning message in FUN(X[[i]], ...):
“input string 1 is invalid UTF-8”
ERROR while rich displaying an object: Error in gsub(" &\\", "\\", r, fixed = TRUE): input string 1 is invalid UTF-8

Traceback:
1. sapply(x, f, simplify = simplify)
2. lapply(X = X, FUN = FUN, ...)
3. FUN(X[[i]], ...)
4. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. doTryCatch(return(expr), name, parentenv, handler)
8. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
9. repr::mime2repr[[mime]](obj)
10. repr_latex.data.frame(obj)
11. gsub(" &\\", "\\", r, fixed = TRUE)
Warning message in grepl("<html.*>", data[["text/html"]], ignore.case = TRUE):
“unable to translate '<table class="dataframe">
<caption>A tibble: 206 × 35</caption>
<thead>
	<tr><th scope=col>country</th><th scope=col>1990</th><th scope=col>1991</th><th scope=col>1992</th><th scope=col>1993</th><th scope=col>1994</th><th scope=col>1995</th><th scope=...' to a wide string”
Warning message in grepl("<html.*>", data[["text/html"]], ignore.case = TRUE):
“input string 1 is invalid”

    country                            1990  1991  1992  1993  1994  1995
1   Afghanistan                        0.285 0.291 0.301 0.311 0.305 0.329
2   Albania                            0.654 0.638 0.622 0.624 0.629 0.638
3   Algeria                            0.595 0.596 0.601 0.603 0.603 0.608
4   Andorra                               NA    NA    NA    NA    NA    NA
5   Angola                                NA    NA    NA    NA    NA    NA
6   Antigua and Barbuda                   NA    NA    NA    NA    NA    NA
7   Argentina                          0.733 0.739 0.743 0.748 0.753 0.754
8   Armenia                            0.663 0.652 0.618 0.621 0.625 0.631
9   Australia                          0.867 0.868 0.868 0.872 0.873 0.882
10  Austria                            0.832 0.835 0.841 0.845 0.851 0.856
11  Azerbaijan                            NA    NA    NA    NA    NA 0.618
12  Bahamas                            0.762 0.762 0.762 0.763 0.765 0.774
13  Bahrain                            0.734 0.728 0.728 0.732 0.732 0.737
14  Bangladesh                         0.397 0.395 0.411 0.419 0.426 0.434
15  Barbados                           0.730 0.732 0.732 0.735 0.740 0.744
16  Belarus                               NA    NA    NA    NA    NA 0.692
17  Belgium                            0.824 0.829 0.845 0.860 0.868 0.875
18  Belize                             0.617 0.626 0.634 0.640 0.643 0.647
19  Benin                              0.351 0.358 0.363 0.371 0.375 0.383
20  Bhutan                                NA    NA    NA    NA    NA    NA
21  Bolivia (Plurinational State of)   0.552 0.561 0.568 0.577 0.586 0.594
22  Bosnia and Herzegovina                NA    NA    NA    NA    NA    NA
23  Botswana                           0.590 0.590 0.589 0.588 0.580 0.583
24  Brazil                             0.641 0.645 0.648 0.654 0.659 0.666
25  Brunei Darussalam                  0.781 0.782 0.782 0.783 0.782 0.784
26  Bulgaria                           0.706 0.706 0.709 0.711 0.713 0.709
27  Burkina Faso                          NA    NA    NA    NA    NA    NA
28  Burundi                            0.294 0.296 0.294 0.265 0.298 0.294
29  Cabo Verde                            NA    NA    NA    NA    NA    NA
30  Cambodia                           0.387 0.392 0.396 0.399 0.400 0.404
⋮   ⋮                                  ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
177 Tonga                              0.641 0.649 0.654 0.660 0.670 0.675
178 Trinidad and Tobago                0.661 0.665 0.665 0.667 0.672 0.677
179 Tunisia                            0.569 0.575 0.582 0.587 0.598 0.606
180 Turkmenistan                          NA    NA    NA    NA    NA    NA
181 Tuvalu                             0.566 0.570 0.566 0.579 0.586 0.587
182 T\xfcrkiye                         0.598 0.602 0.608 0.615 0.616 0.623
183 Uganda                             0.342 0.345 0.339 0.347 0.350 0.356
184 Ukraine                            0.750 0.743 0.733 0.721 0.706 0.702
185 United Arab Emirates               0.713 0.724 0.729 0.736 0.742 0.747
186 United Kingdom                     0.812 0.816 0.824 0.827 0.836 0.835
187 United States                      0.878 0.878 0.882 0.884 0.887 0.888
188 Uruguay                            0.713 0.717 0.719 0.722 0.727 0.729
189 Uzbekistan                            NA    NA    NA    NA    NA    NA
190 Vanuatu                               NA    NA    NA    NA    NA    NA
191 Venezuela (Bolivarian Republic of) 0.658 0.669 0.676 0.680 0.681 0.687
192 Viet Nam                           0.499 0.509 0.521 0.531 0.543 0.556
193 Yemen                              0.359 0.364 0.370 0.377 0.382 0.393
194 Zambia                             0.422 0.416 0.414 0.417 0.413 0.413
195 Zimbabwe                           0.500 0.502 0.487 0.483 0.482 0.477
196 Very high human development        0.797 0.800 0.802 0.804 0.809 0.812
197 High human development             0.569 0.574 0.580 0.586 0.591 0.599
198 Medium human development           0.439 0.440 0.445 0.449 0.453 0.459
199 Low human development              0.346 0.348 0.352 0.356 0.361 0.368
200 Arab States                        0.550 0.552 0.561 0.571 0.577 0.582
201 East Asia and the Pacific          0.514 0.522 0.531 0.541 0.550 0.559
202 Europe and Central Asia            0.674 0.671 0.664 0.659 0.654 0.658
203 Latin America and the Caribbean    0.648 0.653 0.657 0.661 0.666 0.670
204 South Asia                         0.454 0.458 0.464 0.468 0.472 0.478
205 Sub-Saharan Africa                 0.405 0.409 0.408 0.411 0.413 0.420
206 World                              0.608 0.611 0.614 0.617 0.620 0.625
    1996  1997  1998  ⋯ 2014  2015  2016  2017  2018  2019  2020  2021  2022
1   0.334 0.338 0.338 ⋯ 0.497 0.496 0.495 0.496 0.498 0.507 0.501 0.486 0.495
2   0.647 0.645 0.659 ⋯ 0.797 0.797 0.797 0.798 0.801 0.805 0.794 0.794 0.806
3   0.615 0.624 0.634 ⋯ 0.732 0.737 0.743 0.746 0.749 0.753 0.742 0.755 0.761
4      NA    NA    NA ⋯ 0.866 0.869 0.872 0.873 0.875 0.876 0.851 0.871 0.893
5      NA    NA    NA ⋯ 0.577 0.603 0.609 0.610 0.611 0.611 0.610 0.609 0.615
6      NA    NA    NA ⋯ 0.837 0.839 0.842 0.845 0.850 0.851 0.840 0.843 0.848
7   0.760 0.768 0.772 ⋯ 0.855 0.859 0.857 0.861 0.861 0.861 0.851 0.847 0.858
8   0.635 0.644 0.655 ⋯ 0.772 0.777 0.783 0.785 0.789 0.796 0.761 0.786 0.801
9   0.884 0.887 0.891 ⋯ 0.937 0.938 0.939 0.940 0.945 0.947 0.950 0.954 0.952
10  0.861 0.865 0.870 ⋯ 0.919 0.919 0.921 0.922 0.925 0.928 0.925 0.930 0.927
11  0.622 0.626 0.636 ⋯ 0.766 0.771 0.772 0.774 0.775 0.780 0.757 0.765 0.784
12  0.779 0.773 0.777 ⋯ 0.807 0.807 0.808 0.810 0.812 0.800 0.797 0.794 0.818
13  0.741 0.746 0.754 ⋯ 0.847 0.868 0.871 0.874 0.886 0.894 0.885 0.885 0.902
14  0.442 0.451 0.459 ⋯ 0.600 0.621 0.632 0.633 0.646 0.656 0.663 0.663 0.680
15  0.748 0.752 0.754 ⋯ 0.799 0.800 0.803 0.804 0.806 0.808 0.803 0.803 0.807
16  0.697 0.704 0.709 ⋯ 0.825 0.825 0.825 0.828 0.827 0.826 0.815 0.817 0.824
17  0.881 0.884 0.886 ⋯ 0.930 0.933 0.936 0.940 0.942 0.945 0.939 0.948 0.945
18  0.650 0.654 0.657 ⋯ 0.721 0.721 0.727 0.722 0.723 0.725 0.713 0.713 0.717
19  0.389 0.396 0.401 ⋯ 0.509 0.511 0.510 0.507 0.507 0.507 0.504 0.506 0.512
20     NA    NA    NA ⋯ 0.626 0.637 0.647 0.656 0.667 0.680 0.688 0.691 0.695
21  0.602 0.610 0.618 ⋯ 0.701 0.704 0.714 0.715 0.722 0.728 0.697 0.693 0.727
22     NA    NA    NA ⋯ 0.765 0.769 0.776 0.780 0.785 0.788 0.783 0.783 0.799
23  0.584 0.587 0.588 ⋯ 0.685 0.690 0.696 0.704 0.710 0.718 0.718 0.700 0.729
24  0.671 0.676 0.680 ⋯ 0.765 0.764 0.765 0.770 0.774 0.776 0.770 0.768 0.780
25  0.784 0.785 0.785 ⋯ 0.841 0.839 0.838 0.837 0.837 0.835 0.836 0.835 0.825
26  0.718 0.713 0.723 ⋯ 0.819 0.824 0.827 0.829 0.832 0.835 0.826 0.817 0.835
27     NA    NA    NA ⋯ 0.409 0.419 0.427 0.438 0.449 0.453 0.453 0.454 0.457
28  0.292 0.297 0.303 ⋯ 0.431 0.432 0.436 0.434 0.434 0.435 0.435 0.435 0.437
29     NA    NA    NA ⋯ 0.659 0.658 0.661 0.663 0.663 0.667 0.647 0.651 0.664
30  0.408 0.414 0.419 ⋯ 0.557 0.562 0.570 0.578 0.586 0.593 0.595 0.594 0.602
⋮   ⋮     ⋮     ⋮     ⋱ ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
177 0.678 0.680 0.685 ⋯ 0.740 0.743 0.749 0.755 0.759 0.763 0.765 0.763 0.764
178 0.684 0.692 0.700 ⋯ 0.805 0.808 0.806 0.806 0.803 0.805 0.800 0.796 0.805
179 0.616 0.623 0.636 ⋯ 0.725 0.728 0.733 0.737 0.742 0.740 0.733 0.728 0.745
180    NA    NA    NA ⋯ 0.719 0.725 0.729 0.732 0.735 0.741 0.744 0.754 0.761
181 0.587 0.595 0.605 ⋯ 0.650 0.658 0.664 0.668 0.672 0.681 0.681 0.681 0.686
182 0.630 0.638 0.649 ⋯ 0.813 0.821 0.826 0.833 0.838 0.841 0.838 0.841 0.853
183 0.367 0.376 0.386 ⋯ 0.539 0.547 0.553 0.557 0.563 0.569 0.571 0.573 0.578
184 0.701 0.706 0.710 ⋯ 0.788 0.778 0.780 0.785 0.784 0.789 0.783 0.772 0.772
185 0.753 0.761 0.770 ⋯ 0.853 0.857 0.861 0.884 0.901 0.915 0.909 0.903 0.921
186 0.841 0.849 0.856 ⋯ 0.932 0.931 0.934 0.937 0.936 0.941 0.930 0.941 0.946
187 0.890 0.893 0.895 ⋯ 0.926 0.928 0.929 0.931 0.934 0.936 0.925 0.921 0.930
188 0.736 0.747 0.757 ⋯ 0.816 0.818 0.821 0.827 0.826 0.830 0.837 0.837 0.852
189    NA    NA    NA ⋯ 0.703 0.707 0.714 0.719 0.725 0.730 0.723 0.727 0.737
190    NA    NA    NA ⋯ 0.597 0.599 0.603 0.607 0.612 0.622 0.617 0.615 0.621
191 0.690 0.698 0.700 ⋯ 0.770 0.768 0.761 0.749 0.741 0.724 0.699 0.696 0.706
192 0.567 0.578 0.588 ⋯ 0.711 0.717 0.723 0.729 0.737 0.744 0.755 0.754 0.764
193 0.405 0.413 0.423 ⋯ 0.502 0.475 0.467 0.459 0.454 0.458 0.459 0.458 0.466
194 0.415 0.418 0.418 ⋯ 0.559 0.565 0.565 0.570 0.575 0.578 0.578 0.574 0.589
195 0.472 0.472 0.467 ⋯ 0.560 0.567 0.570 0.575 0.586 0.584 0.582 0.581 0.594
196 0.818 0.824 0.829 ⋯ 0.895 0.898 0.900 0.903 0.906 0.909 0.901 0.903 0.908
197 0.607 0.615 0.622 ⋯ 0.739 0.744 0.749 0.754 0.760 0.765 0.763 0.766 0.774
198 0.466 0.472 0.478 ⋯ 0.604 0.611 0.620 0.624 0.627 0.631 0.631 0.629 0.649
199 0.373 0.378 0.382 ⋯ 0.488 0.491 0.497 0.500 0.504 0.507 0.507 0.507 0.512
200 0.590 0.596 0.603 ⋯ 0.688 0.693 0.698 0.702 0.707 0.712 0.707 0.710 0.716
201 0.570 0.579 0.586 ⋯ 0.728 0.735 0.742 0.749 0.756 0.761 0.764 0.768 0.773
202 0.662 0.668 0.674 ⋯ 0.785 0.789 0.793 0.800 0.804 0.808 0.802 0.803 0.815
203 0.676 0.683 0.688 ⋯ 0.765 0.767 0.769 0.772 0.774 0.776 0.764 0.762 0.778
204 0.484 0.490 0.496 ⋯ 0.620 0.627 0.637 0.641 0.642 0.645 0.645 0.641 0.665
205 0.423 0.427 0.430 ⋯ 0.534 0.540 0.543 0.546 0.551 0.557 0.557 0.558 0.565
206 0.631 0.636 0.641 ⋯ 0.726 0.731 0.735 0.739 0.741 0.745 0.742 0.742 0.752
    2023
1   0.496
2   0.810
3   0.763
4   0.913
5   0.616
6   0.851
7   0.865
8   0.811
9   0.958
10  0.930
11  0.789
12  0.820
13  0.899
14  0.685
15  0.811
16  0.824
17  0.951
18  0.721
19  0.515
20  0.698
21  0.733
22  0.804
23  0.731
24  0.786
25  0.837
26  0.845
27  0.459
28  0.439
29  0.668
30  0.606
⋮   ⋮
177 0.769
178 0.807
179 0.746
180 0.764
181 0.689
182 0.853
183 0.582
184 0.779
185 0.940
186 0.946
187 0.938
188 0.862
189 0.740
190 0.621
191 0.709
192 0.766
193 0.470
194 0.595
195 0.598
196 0.914
197 0.777
198 0.656
199 0.515
200 0.719
201 0.775
202 0.818
203 0.783
204 0.672
205 0.568
206 0.756

API bidez datuak normalean tidy formatuan datoz

In [16]:
install.packages("httr")
install.packages("jsonlite")
install.packages("rjstat")

library(httr)
library(jsonlite)
library(rjstat)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘checkmate’



Attaching package: ‘jsonlite’


The following object is masked from ‘package:purrr’:

    flatten

In [17]:


url <- "https://www.eustat.eus/bankupx/api/v1/eu/DB/PX_170112_cpib_pib01d.px"
kontsulta <- '{"query":[]}'
emaitza <- POST(url , body = kontsulta)
taula <- fromJSONstat(content(emaitza, "text"), naming = "label")
BPG <- taula[[1]]
head(BPG)

  lurralde historikoa sektorea                                  datu-mota
1 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
2 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
3 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
4 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
5 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
6 Euskal AE           1. Nekazaritza, abeltzaintza eta arrantza Maila
  neurri-mota                aldia value
1 Uneko prezioak (mila euro) 1995  449513
2 Uneko prezioak (mila euro) 1996  439283
3 Uneko prezioak (mila euro) 1997  466735
4 Uneko prezioak (mila euro) 1998  564307
5 Uneko prezioak (mila euro) 1999  605399
6 Uneko prezioak (mila euro) 2000  514139

**2. JOIN-AK**

Join bat egitea: Bi taula elkartu nahi ditut komunean duten gako baten bidez

In [18]:
superheroiak <- tibble(
  id = c(1, 2, 3),
  izena = c("Batman",
            "Wonder Woman",
            "Superman"))
superheroiak

  id izena
1 1  Batman
2 2  Wonder Woman
3 3  Superman

In [19]:
botereak <- tibble(
  id = c(1, 2, 4),
  boterea = c(
    "Dirua",
    "Lazo magikoa",
    "Mailu erraldoia"))

botereak

  id boterea
1 1  Dirua
2 2  Lazo magikoa
3 4  Mailu erraldoia


**2.1 LEFT JOIN**

Gogoratzeko: "Ez galdu ezkerreko taulako inor"

In [20]:

superheroiak %>%
  left_join(botereak, by = "id")

  id izena        boterea
1 1  Batman       Dirua
2 2  Wonder Woman Lazo magikoa
3 3  Superman     NA


**2.2 INNER JOIN**

Hemen: Bi taulatan daudenak bakarrik azaldu

In [21]:
superheroiak %>%
  inner_join(botereak, by = "id")

  id izena        boterea
1 1  Batman       Dirua
2 2  Wonder Woman Lazo magikoa

**2.3 RIGHT JOIN**

Oraingoan: Eskuineko taulako guztiak mantendu

In [22]:

superheroiak %>%
  right_join(botereak, by = "id")

  id izena        boterea
1 1  Batman       Dirua
2 2  Wonder Woman Lazo magikoa
3 4  NA           Mailu erraldoia

**2.4 FULL JOIN**

Denak sartzen dira

In [23]:

superheroiak %>%
  full_join(botereak, by = "id")

  id izena        boterea
1 1  Batman       Dirua
2 2  Wonder Woman Lazo magikoa
3 3  Superman     NA
4 4  NA           Mailu erraldoia

Ohiko kasu bat

In [25]:
etxeak <- tibble(
  id_etxea = c(1,2,3),
  errenta = c(25000,40000,18000)
)

pertsonak <- tibble(
  id_pertsona = 1:6,
  id_etxea = c(1,1,2,2,2,3),
  adina = c(45,42,38,35,10,70)
)

etxeak
pertsonak

  id_etxea errenta
1 1        25000
2 2        40000
3 3        18000

  id_pertsona id_etxea adina
1 1           1        45
2 2           1        42
3 3           2        38
4 4           2        35
5 5           2        10
6 6           3        70

In [26]:

left_join(
  pertsonak,
  etxeak,
  by = "id_etxea"
)

  id_pertsona id_etxea adina errenta
1 1           1        45    25000
2 2           1        42    25000
3 3           2        38    40000
4 4           2        35    40000
5 5           2        10    40000
6 6           3        70    18000

 Zergatik da left_join normalean erabiliena? Analisi gehienetan nire datu nagusiak mantendu nahi ditut eta informazio gehigarria elkartu